// src/app/api/save/route.ts
import { NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import connectToDatabase from '@/lib/mongodb';
import { Collection } from 'mongodb';
import type { TransactionWithId, DebtItem, StatementItem, OtherLiabilityItem, BudgetItem, WeeklyReviewData } from '@/lib/types';
import { hashData, verifyHash } from '@/lib/storage-utils'; // Use updated hash utils
import { prepareDataForHashing } from '@/lib/prepareDataForHashing'; // Import preparation helper
import stringify from 'fast-json-stable-stringify'; // Import stable stringify
import { Ratelimit } from '@upstash/ratelimit'; // Updated import path if needed for v2
import { kv } from '@vercel/kv';
import { logInfo, logWarn, logError } from '@/lib/logger';

const CLERK_DISABLED_PLACEHOLDER_USER_ID = 'user_2wXc4D8KBDKGhxagoRStZOXnP2Y';

const ratelimit = new Ratelimit({
  redis: kv,
  limiter: Ratelimit.slidingWindow(10, '10 s'), // Allow 10 requests per 10 seconds per user
});

// Define the structure of the incoming request body (should match client's prepared data + hash)
interface SaveDataPayload {
  transactions: TransactionWithId[];
  debts: DebtItem[];
  assetItems: StatementItem[];
  otherLiabilityItems: OtherLiabilityItem[];
  budgetItems: BudgetItem[];
  ownedReviews: Record<string, WeeklyReviewData>;
  startDate?: string; // Date as ISO string
  endDate?: string;   // Date as ISO string
  gettingStartedDismissed?: boolean;
  dataHash: string; // Hash of the prepared data being saved
}

// Helper function to safely replace data in a collection for a specific user
async function replaceCollectionData(db: any, collectionName: string, userId: string, data: any[], session: any) {
    const logContext = { userId, collectionName, operation: 'replaceCollectionData' };
    logInfo(`Starting replace for ${collectionName}`, logContext);
    try {
        const collection: Collection = db.collection(collectionName);
        const dataWithUserIdAndDates = (data || []).map(item => ({
            ...item,
            userId,
            ...(item.date && typeof item.date === 'string' ? { date: new Date(item.date) } : {}),
            ...(item.timestamp && typeof item.timestamp === 'string' ? { timestamp: new Date(item.timestamp) } : {}), // Handle notification timestamps
             // Ensure _id is correctly handled or removed if auto-generated by Mongo
             _id: item._id || undefined // Keep existing _id if present, else let Mongo generate
        }));


        // Optimization: Use bulkWrite for upserts instead of deleteMany + insertMany
        if (dataWithUserIdAndDates.length > 0) {
            const bulkOps = dataWithUserIdAndDates.map(doc => ({
                 updateOne: {
                     filter: { userId: userId, id: doc.id }, // Use the application-generated 'id' for matching
                     update: { $set: { ...doc } }, // Set all fields from the document
                     upsert: true // Create if doesn't exist based on filter
                 }
             }));
             const deleteFilter = { userId, id: { $nin: dataWithUserIdAndDates.map(d => d.id) } };
             logInfo(`Performing deleteMany for ${collectionName} with filter: ${JSON.stringify(deleteFilter)}`, logContext);
             await collection.deleteMany(deleteFilter, { session });
             logInfo(`Performing bulkWrite for ${collectionName} with ${bulkOps.length} operations`, logContext);
            await collection.bulkWrite(bulkOps, { session });
        } else {
             // If no data provided, delete all existing data for the user
             logInfo(`No data provided for ${collectionName}, deleting all existing data for user`, logContext);
            await collection.deleteMany({ userId }, { session });
        }

        logInfo(`Successfully processed ${collectionName}`, logContext);

    } catch (error) {
        logError(`Error replacing ${collectionName}`, error, logContext);
        throw new Error(`Failed to save ${collectionName}`);
    }
}

// Helper function to save/update owned weekly reviews for a specific user
async function saveOwnedWeeklyReviews(db: any, userId: string, ownedReviews: Record<string, WeeklyReviewData>, session: any) {
    const logContext = { userId, operation: 'saveOwnedWeeklyReviews' };
    logInfo(`Starting save for owned weekly reviews`, logContext);
    try {
        const collection: Collection = db.collection('weeklyReviews');
        const reviewKeys = Object.keys(ownedReviews || {});

        if (reviewKeys.length === 0) {
             logInfo(`No owned reviews provided to save.`, logContext);
             return;
        }

        const bulkOps = reviewKeys.map(weekKey => {
            const reviewData = ownedReviews[weekKey];
             if (!reviewData || reviewData.ownerId !== userId) {
                 logWarn(`SECURITY WARNING: Attempted to save review ${weekKey} with mismatched ownerId (expected ${userId}, got ${reviewData?.ownerId}). Skipping.`, logContext);
                 return null;
             }
            const cleanSharedWith = Array.isArray(reviewData.sharedWith) ? reviewData.sharedWith : undefined;

            return {
                 updateOne: {
                     filter: { userId: userId, weekKey: weekKey },
                     update: { $set: { ...reviewData, userId: userId, weekKey: weekKey, sharedWith: cleanSharedWith } },
                     upsert: true
                 }
             };
         }).filter(op => op !== null);


        if (bulkOps.length > 0) {
             logInfo(`Performing bulkWrite for owned weeklyReviews with ${bulkOps.length} operations`, logContext);
             await collection.bulkWrite(bulkOps as any, { session });
             logInfo(`Successfully saved/updated ${bulkOps.length} owned weeklyReviews`, logContext);
         } else {
             logInfo(`No valid owned reviews to save.`, logContext);
         }

    } catch (error) {
        logError(`Error saving owned weeklyReviews`, error, logContext);
        throw new Error('Failed to save owned weekly reviews');
    }
}

// Helper function to save statement dates and getting started state for a specific user
async function saveUserProfileData(db: any, userId: string, startDate?: string, endDate?: string, gettingStartedDismissed?: boolean, session?: any) {
    const logContext = { userId, operation: 'saveUserProfileData' };
    logInfo(`Starting save for user profile data`, logContext);

    // Only proceed if at least one field is provided and defined
    if (startDate === undefined && endDate === undefined && gettingStartedDismissed === undefined) {
        logInfo(`No user profile data fields provided. Skipping profile update.`, logContext);
        return;
    }

    try {
        const collection: Collection = db.collection('userProfiles');
        const updateDoc: { [key: string]: any } = {};

        if (startDate !== undefined) {
            try {
                updateDoc.statementStartDate = startDate ? new Date(startDate) : null;
            } catch { updateDoc.statementStartDate = null; logWarn(`Invalid start date format received: ${startDate}`, logContext); }
        }
        if (endDate !== undefined) {
            try {
                updateDoc.statementEndDate = endDate ? new Date(endDate) : null;
            } catch { updateDoc.statementEndDate = null; logWarn(`Invalid end date format received: ${endDate}`, logContext); }
        }
        if (gettingStartedDismissed !== undefined) {
            updateDoc.gettingStartedDismissed = gettingStartedDismissed;
        }


        if (Object.keys(updateDoc).length > 0) {
             logInfo(`Updating user profile with data: ${JSON.stringify(updateDoc)}`, logContext);
             await collection.updateOne(
                 { userId },
                 { $set: updateDoc },
                 { upsert: true, session } // Pass session if provided
             );
             logInfo(`Successfully saved user profile data`, logContext);
         } else {
              logInfo(`No valid user profile fields to update.`, logContext);
         }

    } catch (error) {
        logError(`Error saving user profile data`, error, logContext);
        throw new Error('Failed to save user profile data');
    }
}

export async function POST(request: Request) {
  const { userId } = auth();
  const logContextBase = { userId: userId || 'unknown', operation: 'POST /api/save' };

  if (!userId) {
    logWarn('Unauthorized save attempt: User not logged in.', logContextBase);
    return NextResponse.json({ error: 'Unauthorized: User not logged in.' }, { status: 401 });
  }

  // Apply Rate Limiting
  const { success, limit, remaining, reset } = await ratelimit.limit(userId);
  const logContextWithRateLimit = { ...logContextBase, rateLimit: { limit, remaining, reset } };

  if (!success) {
      logWarn('Rate limit exceeded.', logContextWithRateLimit);
      return NextResponse.json({ error: 'Too many requests. Please try again later.' }, { status: 429 });
  }
  logInfo('Rate limit check passed.', logContextWithRateLimit);


  let payload: SaveDataPayload;
  try {
    payload = await request.json();
  } catch (error) {
    logError('Invalid request body.', error, logContextWithRateLimit);
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }

  if (!payload || typeof payload !== 'object' || !payload.dataHash) {
      logWarn('Invalid payload structure or missing dataHash.', logContextWithRateLimit);
      return NextResponse.json({ error: 'Invalid payload or missing dataHash' }, { status: 400 });
  }

  const { dataHash, ...receivedData } = payload;

   // Re-prepare the *received* data for hashing on the server-side
   const preparedDataForVerification = prepareDataForHashing(receivedData as any);
   const dataString = stringify(preparedDataForVerification);
   const calculatedServerHash = await hashData(dataString);

    logInfo(`Received hash: ${dataHash}, Calculated server hash: ${calculatedServerHash}`, logContextWithRateLimit);

    const isValid = await verifyHash(dataString, dataHash);

    if (!isValid) {
       logError('Data integrity check failed!', undefined, { ...logContextWithRateLimit, clientHash: dataHash, serverHash: calculatedServerHash });
       // Log truncated data *carefully* if needed for debugging, avoid full sensitive data
        // console.log("Data that resulted in hash mismatch (truncated):", dataString.substring(0, 300) + (dataString.length > 300 ? "..." : ""));
       return NextResponse.json({ error: 'Data integrity check failed. Save aborted.' }, { status: 400 });
    }
    logInfo('Data integrity check passed. Proceeding with save.', logContextWithRateLimit);

  const client = await connectToDatabase();
  const db = client.db();
  const session = client.startSession(); // Start MongoDB session

  try {
    logInfo('Starting MongoDB transaction.', logContextWithRateLimit);
    await session.withTransaction(async () => {
        const {
          transactions = [],
          debts = [],
          assetItems = [],
          otherLiabilityItems = [],
          budgetItems = [],
          ownedReviews = {},
          startDate,
          endDate,
          gettingStartedDismissed
        } = preparedDataForVerification;

        // Perform all database operations within the transaction
        await Promise.all([
            replaceCollectionData(db, 'transactions', userId, transactions, session),
            replaceCollectionData(db, 'debts', userId, debts, session),
            replaceCollectionData(db, 'assetItems', userId, assetItems, session),
            replaceCollectionData(db, 'otherLiabilityItems', userId, otherLiabilityItems, session),
            replaceCollectionData(db, 'budgetItems', userId, budgetItems, session),
            saveOwnedWeeklyReviews(db, userId, ownedReviews, session),
            saveUserProfileData(db, userId, startDate, endDate, gettingStartedDismissed, session)
        ]);
    });
    logInfo('MongoDB transaction committed successfully.', logContextWithRateLimit);
    return NextResponse.json({ message: `Data saved successfully for user ${userId}` });
  } catch (error: any) {
    // Transaction automatically aborted on error by withTransaction
    logError('MongoDB transaction failed or aborted.', error, logContextWithRateLimit);
    const errorMessage = error instanceof Error ? error.message : 'Failed to save data to database';
    return NextResponse.json({ error: errorMessage }, { status: 500 });
  } finally {
     await session.endSession(); // Ensure session is always closed
     logInfo('MongoDB session ended.', logContextWithRateLimit);
  }
}
