// src/app/api/save/route.ts
import { NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server'; // Re-enabled Clerk
import connectToDatabase from '@/lib/mongodb';
import { Collection, ClientSession } from 'mongodb'; // Import ClientSession
import type { TransactionWithId, DebtItem, StatementItem, OtherLiabilityItem, BudgetItem, WeeklyReviewData } from '@/lib/types';
import { hashData, verifyHash } from '@/lib/storage-utils'; // Use updated hash utils
import { prepareDataForHashing } from '@/lib/prepareDataForHashing'; // Import preparation helper
import stringify from 'fast-json-stable-stringify'; // Import stable stringify
import { Ratelimit } from '@upstash/ratelimit';
import { kv } from '@vercel/kv';
import { logInfo, logWarn, logError } from '@/lib/logger'; // Use server logger
import { addCorsHeaders } from '@/lib/utils'; // Import CORS helper

// const CLERK_DISABLED_PLACEHOLDER_USER_ID = 'user_2wXc4D8KBDKGhxagoRStZOXnP2Y'; // Clerk enabled

const ratelimit = new Ratelimit({
  redis: kv,
  limiter: Ratelimit.slidingWindow(10, '10 s'), // Allow 10 requests per 10 seconds per user
});

// Define the structure of the incoming request body (should match client's prepared data + hash)
interface SaveDataPayload {
  transactions: TransactionWithId[];
  debts: DebtItem[];
  assetItems: StatementItem[];
  otherLiabilityItems: OtherLiabilityItem[];
  budgetItems: BudgetItem[];
  ownedReviews: Record<string, WeeklyReviewData>;
  startDate?: string; // Date as ISO string
  endDate?: string;   // Date as ISO string
  gettingStartedDismissed?: boolean;
  dataHash: string; // Hash of the prepared data being saved
}

// Helper function to safely replace data in a collection for a specific user using a transaction session
async function replaceCollectionData(db: any, collectionName: string, userId: string, data: any[], session: ClientSession) { // Accept session
    const logContext = { userId, collectionName, operation: 'replaceCollectionData' };
    logInfo(`Save API: Starting replace for ${collectionName}`, logContext);
    try {
        const collection: Collection = db.collection(collectionName);
        // Data received should already have Dates converted to ISO strings by prepareDataForHashing on client
        // Convert back to Date objects before saving to MongoDB where applicable
        const dataWithUserIdAndDates = (data || []).map(item => ({
            ...item,
            userId,
            ...(item.date && typeof item.date === 'string' ? { date: new Date(item.date) } : {}), // Convert 'date' string back to Date
            ...(item.timestamp && typeof item.timestamp === 'string' ? { timestamp: new Date(item.timestamp) } : {}), // Handle notification timestamps
            // Ensure _id is correctly handled or removed if auto-generated by Mongo
            _id: item._id || undefined // Keep existing _id if present, else let Mongo generate
        }));


        const itemIdsToKeep = new Set(dataWithUserIdAndDates.map(d => d.id));

        // Delete documents for the user that are *not* in the incoming data list
        const deleteFilter = { userId, id: { $nin: Array.from(itemIdsToKeep) } };
        logInfo(`Save API: Performing deleteMany for ${collectionName} with filter: ${JSON.stringify(deleteFilter)}`, logContext);
        await collection.deleteMany(deleteFilter, { session });


        // Upsert documents from the incoming list
        if (dataWithUserIdAndDates.length > 0) {
            const bulkOps = dataWithUserIdAndDates.map(doc => ({
                 updateOne: {
                     filter: { userId: userId, id: doc.id }, // Use the application-generated 'id' for matching
                     update: { $set: { ...doc, userId: userId } }, // Ensure userId is set correctly
                     upsert: true // Create if doesn't exist based on filter
                 }
             }));
             logInfo(`Save API: Performing bulkWrite for ${collectionName} with ${bulkOps.length} operations`, logContext);
            await collection.bulkWrite(bulkOps, { session });
        } else {
             logInfo(`Save API: No data provided for ${collectionName}, deleted existing data.`, logContext);
        }

        logInfo(`Save API: Successfully processed ${collectionName}`, logContext);

    } catch (error) {
        logError(`Save API: Error replacing ${collectionName}`, error, { ...logContext, stack: error instanceof Error ? error.stack : undefined });
        throw new Error(`Failed to save ${collectionName}`);
    }
}


// Helper function to save/update owned weekly reviews for a specific user using a transaction session
async function saveOwnedWeeklyReviews(db: any, userId: string, ownedReviews: Record<string, WeeklyReviewData>, session: ClientSession) { // Accept session
    const logContext = { userId, operation: 'saveOwnedWeeklyReviews' };
    logInfo(`Save API: Starting save for owned weekly reviews`, logContext);
    try {
        const collection: Collection = db.collection('weeklyReviews');
        const reviewKeys = Object.keys(ownedReviews || {});

        if (reviewKeys.length === 0) {
             logInfo(`Save API: No owned reviews provided to save.`, logContext);
             return;
        }

        const bulkOps = reviewKeys.map(weekKey => {
            const reviewData = ownedReviews[weekKey];
             if (!reviewData || reviewData.ownerId !== userId) {
                 logWarn(`Save API: SECURITY WARNING: Attempted to save review ${weekKey} with mismatched ownerId (expected ${userId}, got ${reviewData?.ownerId}). Skipping.`, logContext);
                 return null;
             }
            const cleanSharedWith = Array.isArray(reviewData.sharedWith) ? reviewData.sharedWith : undefined;

            return {
                 updateOne: {
                     filter: { userId: userId, weekKey: weekKey }, // Use userId (ownerId) and weekKey
                     update: { $set: { ...reviewData, userId: userId, weekKey: weekKey, sharedWith: cleanSharedWith } }, // Ensure userId and weekKey are set
                     upsert: true
                 }
             };
         }).filter(op => op !== null);


        if (bulkOps.length > 0) {
             logInfo(`Save API: Performing bulkWrite for owned weeklyReviews with ${bulkOps.length} operations`, logContext);
             await collection.bulkWrite(bulkOps as any, { session }); // Pass session
             logInfo(`Save API: Successfully saved/updated ${bulkOps.length} owned weeklyReviews`, logContext);
         } else {
             logInfo(`Save API: No valid owned reviews to save.`, logContext);
         }

    } catch (error) {
        logError(`Save API: Error saving owned weeklyReviews`, error, { ...logContext, stack: error instanceof Error ? error.stack : undefined });
        throw new Error('Failed to save owned weekly reviews');
    }
}

// Helper function to save user profile data using a transaction session
async function saveUserProfileData(db: any, userId: string, startDate?: string, endDate?: string, gettingStartedDismissed?: boolean, session?: ClientSession) { // Accept optional session
    const logContext = { userId, operation: 'saveUserProfileData' };
    logInfo(`Save API: Starting save for user profile data`, logContext);

    // Only proceed if at least one field is provided and defined
    if (startDate === undefined && endDate === undefined && gettingStartedDismissed === undefined) {
        logInfo(`Save API: No user profile data fields provided. Skipping profile update.`, logContext);
        return;
    }

    try {
        const collection: Collection = db.collection('userProfiles');
        const updateDoc: { [key: string]: any } = {};

        if (startDate !== undefined) {
            try {
                updateDoc.statementStartDate = startDate ? new Date(startDate) : null;
            } catch { updateDoc.statementStartDate = null; logWarn(`Save API: Invalid start date format received: ${startDate}`, logContext); }
        }
        if (endDate !== undefined) {
            try {
                updateDoc.statementEndDate = endDate ? new Date(endDate) : null;
            } catch { updateDoc.statementEndDate = null; logWarn(`Save API: Invalid end date format received: ${endDate}`, logContext); }
        }
        if (gettingStartedDismissed !== undefined) {
            updateDoc.gettingStartedDismissed = gettingStartedDismissed;
        }


        if (Object.keys(updateDoc).length > 0) {
             logInfo(`Save API: Updating user profile with data: ${JSON.stringify(updateDoc)}`, logContext);
             await collection.updateOne(
                 { userId },
                 { $set: updateDoc },
                 // Use upsert true. Pass session if provided (critical for transaction)
                 session ? { upsert: true, session } : { upsert: true }
             );
             logInfo(`Save API: Successfully saved user profile data`, logContext);
         } else {
              logInfo(`Save API: No valid user profile fields to update.`, logContext);
         }

    } catch (error) {
        logError(`Save API: Error saving user profile data`, error, { ...logContext, stack: error instanceof Error ? error.stack : undefined });
        throw new Error('Failed to save user profile data');
    }
}

// Handle OPTIONS request for CORS preflight
export async function OPTIONS() {
  const response = new NextResponse(null, { status: 200 });
  addCorsHeaders(response);
  return response;
}

export async function POST(request: Request) {
  const { userId } = auth();
  const logContextBase = { userId: userId || 'unknown', operation: 'POST /api/save' };

  if (!userId) {
    logWarn('Save API: Unauthorized save attempt: User not logged in.', logContextBase);
    const response = NextResponse.json({ error: 'Unauthorized: User not logged in.' }, { status: 401 });
    return addCorsHeaders(response); // Add CORS headers to error response
  }

  // Apply Rate Limiting
  const { success, limit, remaining, reset } = await ratelimit.limit(userId);
  const logContextWithRateLimit = { ...logContextBase, rateLimit: { limit, remaining, reset } };

  if (!success) {
      logWarn('Save API: Rate limit exceeded.', logContextWithRateLimit);
       const response = NextResponse.json({ error: 'Too many requests. Please try again later.' }, { status: 429 });
       return addCorsHeaders(response);
  }
  logInfo('Save API: Rate limit check passed.', logContextWithRateLimit);


  let payload: SaveDataPayload;
  try {
    payload = await request.json();
  } catch (error) {
    logError('Save API: Invalid request body.', error, { ...logContextWithRateLimit, stack: error instanceof Error ? error.stack : undefined });
    const response = NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
    return addCorsHeaders(response);
  }

  if (!payload || typeof payload !== 'object' || !payload.dataHash) {
      logWarn('Save API: Invalid payload structure or missing dataHash.', logContextWithRateLimit);
       const response = NextResponse.json({ error: 'Invalid payload or missing dataHash' }, { status: 400 });
       return addCorsHeaders(response);
  }

  const { dataHash, ...receivedData } = payload;

   // Re-prepare the *received* data for hashing on the server-side
   const preparedDataForVerification = prepareDataForHashing(receivedData as any);
   const dataString = stringify(preparedDataForVerification);
   const calculatedServerHash = await hashData(dataString);

    logInfo(`Save API: Received hash: ${dataHash}, Calculated server hash: ${calculatedServerHash}`, logContextWithRateLimit);

    const isValid = await verifyHash(dataString, dataHash);

    if (!isValid) {
       logError('Save API: Data integrity check failed!', undefined, { ...logContextWithRateLimit, clientHash: dataHash, serverHash: calculatedServerHash });
       // Log truncated data *carefully* if needed for debugging, avoid full sensitive data
       // logInfo("Data that resulted in hash mismatch (truncated):", { dataStringTruncated: dataString.substring(0, 300) + (dataString.length > 300 ? "..." : "") }, logContextWithRateLimit);
       const response = NextResponse.json({ error: 'Data integrity check failed. Save aborted.' }, { status: 400 });
       return addCorsHeaders(response);
    }
    logInfo('Save API: Data integrity check passed. Proceeding with save.', logContextWithRateLimit);

  const client = await connectToDatabase();
  const db = client.db();
  const session = client.startSession(); // Start MongoDB session

  try {
    logInfo('Save API: Starting MongoDB transaction.', logContextWithRateLimit);
    await session.withTransaction(async () => {
        // Use the verified prepared data for saving
        const {
          transactions = [],
          debts = [],
          assetItems = [],
          otherLiabilityItems = [],
          budgetItems = [],
          ownedReviews = {},
          startDate,
          endDate,
          gettingStartedDismissed
        } = preparedDataForVerification;


        // Perform all database operations within the transaction
        await Promise.all([
            replaceCollectionData(db, 'transactions', userId, transactions, session),
            replaceCollectionData(db, 'debts', userId, debts, session),
            replaceCollectionData(db, 'assetItems', userId, assetItems, session),
            replaceCollectionData(db, 'otherLiabilityItems', userId, otherLiabilityItems, session),
            replaceCollectionData(db, 'budgetItems', userId, budgetItems, session),
            saveOwnedWeeklyReviews(db, userId, ownedReviews, session),
            // Pass the gettingStartedDismissed value to the profile update function
            saveUserProfileData(db, userId, startDate, endDate, gettingStartedDismissed, session)
        ]);
    });
    logInfo('Save API: MongoDB transaction committed successfully.', logContextWithRateLimit);
     const response = NextResponse.json({ message: `Data saved successfully for user ${userId}` });
     return addCorsHeaders(response);
  } catch (error: any) {
    // Transaction automatically aborted on error by withTransaction
    logError('Save API: MongoDB transaction failed or aborted.', error, { ...logContextWithRateLimit, stack: error.stack });
    const errorMessage = error instanceof Error ? error.message : 'Failed to save data to database';
     const response = NextResponse.json({ error: errorMessage }, { status: 500 });
     return addCorsHeaders(response);
  } finally {
     await session.endSession(); // Ensure session is always closed
     logInfo('Save API: MongoDB session ended.', logContextWithRateLimit);
  }
}
